version: '3.4'

services:
  web:
    tty: true
    stdin_open: true
    stop_grace_period: 1s
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - rails_bundle:/usr/local/bundle
      - ./:/app
    command: /app/entrypoint.sh

volumes:
  rails_bundle:
